version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:7000'
    ports:
      - 7000:7000
    volumes:
      - .:/app
    tty: true
    depends_on:
      - db

  queue:
      build:
        context: .
        dockerfile: Dockerfile
      command: 'python consumer.py'
      depends_on:
        - db

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306